### ISSUE TITLE
Implement something like the new Twitter Circles

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#103]
https://www.engadget.com/twitter-circles-test-183333627.html

Twitter has just started testing a new feature to limit posts to a circle of 150 people (dunbar!!) instead of going full public.

To me, this seems like a really nice solution for people. You don't need a separate "priv" account for closer friends. And you don't need to manage a bunch of private groups.

In Iris, I suppose this would involve creating an encrypted list of 150 of your friends. You share the read key to these people. Then you can always revoke a read key from someone if you remove them from the list.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
