### ISSUE TITLE
Yarn Dev problem: URL breaks when using in a different tab or refreshing the same tab

### ISSUE THREAD

**Issue by itsvetobaby** [irislib/iris-messenger#115]
Hi, when refreshing a profile like 
http://localhost:8080/profile/hyECQHwSo7fgr2MVfPyakvayPeixxsaAWVtZ-vbaiSc.TXIp8MnCtrnW6n2MrYquWPcc-DTmZzMBmc2yaGv9gIU

i get a http error 

```
Cannot GET /profile/hyECQHwSo7fgr2MVfPyakvayPeixxsaAWVtZ-vbaiSc.TXIp8MnCtrnW6n2MrYquWPcc-DTmZzMBmc2yaGv9gIU
```

in both brave and chrome

If this has been diagnosed but not yet fixed i can try if you put the problem in a comment :)

**Comment by mmalmi** [comment]
True, that's annoying. Not sure how to fix this on the preact dev server.

**Comment by mmalmi** [comment]
Fixed by moving to # routing.
