### ISSUE TITLE
Features request for iris-messenger in general

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [irislib/iris-messenger#116]
![image](https://user-images.githubusercontent.com/67427045/174442484-44266dd4-d2ac-448e-bf69-6a8cec8ba58b.png)

All the features here, except the Cesium related ones, i would add to iris-messenger if i was you.
They are not metaverse related, but related to decentralization, privacy and security.

The integrated browser is disputable maybe (but fits just too good in), but the peer-cdn https://github.com/vardius/peer-cdn from the browser section, iris-messenger needs for sure. iris-messenger is already bleeding edge technology. it should stay that way. 😍 

👏 Applause to everybody

**Comment by petrikaj** [comment]
Iris is a nostr client now.
