### ISSUE TITLE
Bug - popup text hides behind menu

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [irislib/iris-messenger#126]
![image](https://user-images.githubusercontent.com/67427045/174669781-d4ecde72-3b94-4afe-9be5-abdbdb374108.png)

**Comment by mmalmi** [comment]
Would you be willing to fix it? 🙂

**Comment by worldpeaceenginelabs** [comment]
well, i just made my first steps in preact/react territory and modified successfully the router.

but i am always willing to help...

I will try, maybe I can even create a proper pull request, this time 😂

**Comment by worldpeaceenginelabs** [comment]
![image](https://user-images.githubusercontent.com/67427045/174913114-0520a016-92f9-4d7a-99a9-ce56692a5c69.png)

How is that? I think it looks cool, but i dont like the way i did it.

Other resolutions could cause problems (closer to the top or further etc.)
I would have gone for the z-index, but it does not what i wished.

Before
```
/* Position the tooltip text */
  position: absolute;
  z-index: 1;
  right: 0;
  top: 100%;
  margin-left: -60px;
```


After
```
 /* Position the tooltip text */
  position: absolute;
  z-index: 1;
  left: 120%;
  top: -25%;
```

Pull request worthy?

**Comment by worldpeaceenginelabs** [comment]
![image](https://user-images.githubusercontent.com/67427045/174924272-4aa3968f-af22-4988-bee7-5e3aa6719197.png)

hmmm... can I make a pull request at all?

**Comment by mmalmi** [comment]
Thank you! You can put that individual change into another branch that is forked from this repo (irislib/iris-messenger), and then pull request it.

Can you make a tooltip-right class for this element, so we don't change the behavior of other existing tooltips?

**Comment by worldpeaceenginelabs** [comment]
yes of course.

ill be back in my codecave later, then ill do.

**Comment by worldpeaceenginelabs** [comment]
![image](https://user-images.githubusercontent.com/67427045/175121239-24dd692e-9f9f-4bef-8350-73c19217c6aa.png)

Well, maybe not 😅
This is from when i updated my new branch with your commits.

I didnt do the fix commit yet.
![image](https://user-images.githubusercontent.com/67427045/175121501-28e28418-1486-4c6f-b50d-6931f53bfcc2.png)

**Comment by worldpeaceenginelabs** [comment]
i deleted my progress 😭

good thing: i learned something so that will never happen again.
bad thing: i have to start over tonight... rrrr

**Comment by petrikaj** [comment]
Iris is a nostr client now.
