### ISSUE TITLE
Which peer / relay node to use?

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#135]
The best way to use Iris is with only one peer. But which peer is the best at any given moment?

The peers change so often. My mobile is using https://gun-rs.iris.to/gun because I thought I could get the benefits of using the new rust code that way.

But my desktop is using https://gun-us.herokuapp.com/gun and it seems like most activity is on that one these days.

Why doesn't multiple peers work well yet? What needs to happen for it to work?

**Comment by mmalmi** [comment]
Have you tried multiple peers recently? I'm using both peers and it's working fine.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
