### ISSUE TITLE
Possible security issue with shared invitation link?

### ISSUE THREAD

**Issue by bart** [irislib/iris-messenger#140]
Hey everyone,

I checked the Iris lib code, especially the method for chat link generation (createChatLink) which is used in Iris messenger to create a new conversation. As far as I can see this link is always the same (except for manual created additional links).

So my question is this: If Alice invites Bob sharing her invitation link and Bob stores this key (secret and link ID). Isn't he always able to watch this "shared users" private graph `chatRequests` also for additional invitations Alice will send to other people so that he can sneak into their communication?

Maybe I missed something so please feel free to reply with an explanation which would be highly appreciated.

Thanks!

**Comment by mmalmi** [comment]
Chat links are only used for chat requests: "hey, here's my public key, I have messages for you in my outbox". Messages themselves are encrypted between your public keys, and no one else can read them.

Everyone with the chat link, however, can monitor or even delete incoming requests to the chat link. Or spam you with chat requests. Sharing your chat links publicly is subject to trolling.

**Comment by bart** [comment]
Thanks for your reply @mmalmi! I think the `useChatLink()` method does more than just "Thanks for your public key, now I know you." As you mentioned it also puts the public key of the second user into chatRequests property wich is readable by the shared secret. So in https://github.com/irislib/iris-messenger/blob/03c78d79982652f5a3dfdf529e9c29cafd8d831d/src/js/iris-lib/Channel.js#L518 it adds a participant using the public key. My concern is now: If I know both public keys and the secret: Shouldn't I be able to "add myself" to that "secret chat of both parties", too so that I can spy their messages?

Maybe I missed something here? Thanks!!

**Comment by mmalmi** [comment]
That function is only used for group chats. Group chats and private chats work differently, although they're in the same Channel class.

Secret from the invite link is only used to encrypt things in the chat request. For the private chat itself, a new secret is calculated between the public keys using the ECDH algorithm (with [Gun.SEA.secret()](https://github.com/irislib/iris-messenger/blob/03c78d79982652f5a3dfdf529e9c29cafd8d831d/src/js/iris-lib/Channel.js#L321)).

**Comment by bart** [comment]
Where in the code (Channel class) does it differentiate between private and group chat? Both use the `useChatLink()` method and `getMyChatLinks()` will finally create the channel then, correct? Sorry for that many questions but I really want to understand what I missed here.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
