### ISSUE TITLE
Tauri

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#164]
I just saw that Tauri (cross-platform Electron alternative) has released the alpha for mobile support 

https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/

**Comment by trosel** [comment]
Looks like it's happening? https://github.com/irislib/iris-messenger/commit/b9c002c2e3a02f6ebabf4853de06d55f716e62c5

**Comment by petrikaj** [comment]
[Noted!](https://tree.taiga.io/project/iristoapp-iris-messenger/issue/885)
