### ISSUE TITLE
Show on my feed a button to show new messages. Something like what twitter does.

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#165]
Hi,

I'm testing Iris with Nostr and I really would like to see on home window, when new messages come from people that I follow, a button called like: "Show 30 new messages". Something like what Twitter does.
The way works now, I need to hard refresh to see new messages.

**Comment by mmalmi** [comment]
I have made it update every 3 seconds now. I'll make it update in real-time next and then add "show new messages".

**Comment by bitcoinuser** [comment]
Done
