### ISSUE TITLE
Bug: on my Home feed, sometimes a person I follow post something but don't appear on my feed.

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#166]
Hi,

I looked at other Nostr client: https://nostr.io/p/82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2 for messages of Jack and I see that some messages he posted do not appear on my Iris home feed. (I follow him)

**Comment by mmalmi** [comment]
The feed is going through lots of changes, and the connected relays might also be at fault. Any better now?

**Comment by bitcoinuser** [comment]
Hi, looks like this problem yes, but now sometimes when I click to see show replied message and then I go to Home again, I see on my feed all posts from the user of show replied messages. 
I would like to see who replied message as a thread, something like this: https://phrasetown.com/

**Comment by bitcoinuser** [comment]
I dont understand other thing: Why to show the feed, https://phrasetown.com/ is much faster and lighter than Iris?
https://phrasetown.com/ use Farcaster that is similar with Nostr.

**Comment by bitcoinuser** [comment]
Will close this issue. But for sure My feed do not show only the posts of people I follow. I don't know why.

**Comment by mmalmi** [comment]
> https://phrasetown.com/

Judging by the requests it makes, it's not similar to nostr, but a centralized service. It only calls some http server that probably curates the feed and caches it. No websockets.

**Comment by bitcoinuser** [comment]
> > https://phrasetown.com/
> 
> Judging by the requests it makes, it's a centralized service, not similar to nostr. It only calls some http server that probably curates the feed and caches it. No websockets.

Understood. Thanks. I sent you a DM on Telegram, about some problems.
