### ISSUE TITLE
Bug: Number of followers/following of persons I follow, show wrong data.

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#167]
Hi,

I follow Jack on Iris and the numbers of following/followers is very different of what appear here: https://nostr.io/p/82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2

**Comment by mmalmi** [comment]
Iris only subscribes to events from followed users and their follows (2nd degree follows). That's also reflected in follower counts. If the following count is different, that means either one of the clients has received old data.

I also made updates to the follow system today. Working any better?

**Comment by petrikaj** [comment]
This has been updated in the recent upgrades and should be resolved now.
