### ISSUE TITLE
timestamp links are missing /#/

### ISSUE THREAD

**Issue by melvincarvalho** [irislib/iris-messenger#177]
When clicking on a timestamp it goes to:

https://iris.to/post/note1fh8szpt9t7wplchu8dqdkqt83qnzht5kc55mv0ly705lkysw09sqqzg58c

but is missing the /#/

should be: 

https://iris.to/#/post/note1fh8szpt9t7wplchu8dqdkqt83qnzht5kc55mv0ly705lkysw09sqqzg58c

Alternatively the server side could render the first link, which would help with indexing, `#` in web architecture has an overloaded meaning wrt single page apps

**Comment by silverbucket** [comment]
Not just timestamp links, but also profile links. When viewing someone else's follows/followers, the links are generated without the `#` as well:

Actual:
https://iris.to/profile/f5a2d7a8ba39606e5895f66d89412f3ceb007df5dc6a23bc45cc510327435f09

Expected:
https://iris.to/#/profile/f5a2d7a8ba39606e5895f66d89412f3ceb007df5dc6a23bc45cc510327435f09

**Comment by mmalmi** [comment]
Ah, true. Preact-router handles them fine when you click them, but they won't work if you open them in a new tab.

I think I moved to # urls because of some issue in the electron app. But we could move back to normal routing and make netlify serve the paths used by the application.

**Comment by melvincarvalho** [comment]
Ah, I use preact alot too

Different trade-offs there

I'd perhaps lean towards the normal routing path, personally, even though it can be a bit of a pain to set up

Some advantages with bookmarking, sharing, search, right now, and I think there will be more in future

**Comment by petrikaj** [comment]
The syntax has been changed so closing this.
