### ISSUE TITLE
The number of relays I'm connected start with 10 then go to 2 or 3 and I don't know why this happens. A bug?

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#200]
Hi,

The number of relays I'm connected start with 10 then go to 2 or 3 and I don't know why this happens. A bug?

Thanks.

**Comment by yomajo** [comment]
Same here. Increasing number of relays works for a while, eventually number of relays will converge to 2-4 and number of shown relays won't be higher than 10, even though more had been added before.

I consider this to be a serious issue and would appreciate this issue being bumped in priorities. Not a ts/js dev myself, unfortunately.

**Comment by mmalmi** [comment]
Can you check the console logs and filter for `notice`s? It might be sending too big or too many queries and get disconnected by relays.

**Comment by yomajo** [comment]
I was using web client (iris.to), testing different clients, maybe some sync issue at protocol level kept deleting added relays, don't know if relay info is carried with account pub/prv key info.

Will let you know if issue reappears and under what circumstances.

**Comment by petrikaj** [comment]
The way relays work on iris has been changed since the Feb so closing this now.
