### ISSUE TITLE
Feature request Adding Friend button

### ISSUE THREAD

**Issue by snapo** [irislib/iris-messenger#206]
Just had a discussion with someone that did not know how to add a friend in Iris / or follow someone where you only know the npub.
i told the person that he can click on his profile and change the url, or if he shares a link to include the url.

It might be good to have a button on the left side main menu to add a Friend, then the users can parse in the npub address.

![image](https://user-images.githubusercontent.com/6347922/214185810-404a7fbc-805c-4ab3-aa9b-3f0f000a7ef3.png)

**Comment by petrikaj** [comment]
Follow features [added](https://docs.iris.to/features/users#follow-and-unfollow). Also with QR codes.
