### ISSUE TITLE
If I hibernate notebook with iris page opened, then I come back from hibernate mode, I need to refresh iris to see new notes.

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#207]
Hi,

If I hibernate notebook with iris page opened, then I come back from hibernate mode, I need to refresh iris page to see new notes.

On twitter, doing the same thing, I don't need to refresh twitter page.

**Comment by petrikaj** [comment]
The feed functionality has changed a lot since. Open a new issue if this is still relevant.
