### ISSUE TITLE
Error running development server

### ISSUE THREAD

**Issue by fiatjaf** [irislib/iris-messenger#212]
When running `yarn dev` I get this:

`error:0308010C:digital envelope routines::unsupported`

![2023-01-24-155206_958x1035_scrot](https://user-images.githubusercontent.com/1653275/214382612-9ec37ba9-909c-4061-b66e-6668336a0a39.png)

**Comment by mmalmi** [comment]
Found this https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

Author of the iris-messenger dockerfile took the approach `NODE_OPTIONS=--openssl-legacy-provider yarn serve`. Or maybe node version can be specified in package.json or somewhere.
