### ISSUE TITLE
My profile page doesn't have a button for self DM

### ISSUE THREAD

**Issue by inakil** [irislib/iris-messenger#219]
Hi, I'm not sure if this is the proper place to bring this. 

Anyway, I can send DM from the profile page of other people I'm following, but I cannot find a button for self DM, both in desktop browser (firefox) and Android App (which I think calls my android firefox browser behind).

My work-around was to self DM from another client (astral.ninja), and then that self message apperead in my "Messages" page. Now I can continue chats with myself from here on, but I think allowing a self DM from the start using the same interface already present in others people's profiles would be better.

**Comment by mmalmi** [comment]
Added
