### ISSUE TITLE
Feature request: Implement a back button that keeps the position in the feed

### ISSUE THREAD

**Issue by YellowWords** [irislib/iris-messenger#224]
So currently I have a bit of a UX issue with Iris, let me see if I can explain it properly:

When I use Nostr I usually start reading the feed from the top - Then when I see a discussion that looks interesting I click on that note and read the tread a bit, then jump back out to the feed and keep reading.

Some client such as Astral or Hamstr for instance have a back button in the UI - When you hit this you go back to the last feed _and the position you had in the feed_. This last part is pretty important as otherwise you lose your place in it and have to find it again, which can be pretty annoying if it's your follows for instance which is a pretty long feed.

Iris does not do this - There's no back button in the GUI and if you hit the back button in the browser you go back to the top of the last feed you where in (the position is not retained).

Let me know if that explanation makes sense for you, otherwise I could try capturing a GIF or something to better illustrate what I mean. Thanks for your work on Iris!

**Comment by YellowWords** [comment]
Ah I just saw this was already requested in #188, my bad.

**Comment by mmalmi** [comment]
Maybe the most requested & important feature atm
