### ISSUE TITLE
Pictures aren't shown correctly.

### ISSUE THREAD

**Issue by LeonardoGitHubAlt** [irislib/iris-messenger#234]
Errors report in browser console:
Failed to load “https://proxy.irismessengers.wtf/insecure/rs:fill:80:80/plain/https://cdn.jb55.com/img/red-me.jpg”. A ServiceWorker passed an Error Response to FetchEvent.respondWith(). This typically means the ServiceWorker performed an invalid fetch() call.

**Comment by LeonardoGitHubAlt** [comment]
Errors report in browser console:
Failed to load “https://proxy.irismessengers.wtf/insecure/rs:fill:80:80/plain/https://cdn.jb55.com/img/red-me.jpg”. A ServiceWorker passed an Error Response to FetchEvent.respondWith(). This typically means the ServiceWorker performed an invalid fetch() call.

**Comment by petrikaj** [comment]
The way images work on Iris has been changed since. Closing this for now.
