### ISSUE TITLE
Zap Fundraiser [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#239]
## User Story ##
As a pleb Iris user who wants to propose support of a noble cause, I would like the capability to create a fundraise post, so that I can prompt the plebs to considering donating to my proposed cause (for example, donate to Bitcoin Beach community etc).

### Acceptance Criteria ###
A pleb using Damus can create a fundraiser, which contains the following info:
1. Initiator of fundraiser npub, and
2. Title (for instance, Bitcoin Beach school funds fundraiser), and
3. npub of organization/person(s) [for instance, Bitcoin Beach], and
4. Optional link to organization/person (for instance, https://www.bitcoinbeach.com/), and
5. Days to go (for instance, 10 days to go) [time remaining calculated from default 28 days], and
6. Target amount [custom value set by pleb initiating fundraiser; e.g. 1,000,000 SATS], and
7. Display % funded [for instance, 42% funded], and
8. Display XX SATS pledged of YY SATS goal (for instance, 420,000 SATS pledged of 1,000,000 SATS goal), and
9. Display number of plebs who have donated (for instance, 1031 plebs have donated), and
10. Plebs can donate any amount of one (1) or more SAT of their choosing.

Request via @wtogami

"_`What's the simplest way to post a fund raiser here? Can you post a WOS link in  your profile and within notes? I've never tried WOS myself because I use only CLN. I'm recommending stuff to a user that can't run their own node at the moment.`_"

"_`They don't have iOS. They would probably use Tor Browser and Iris.`_"

https://damus.io/note1pel7p768m427unrq6h88g3ae8rx6g2f2clkju0ss3lew87rep0fsv7wqxh

**Comment by alltheseas** [comment]
@petrikaj is zapraiser thrown in the trash, or placed on the roadmap?

**Comment by petrikaj** [comment]
It's been [noted](https://tree.taiga.io/project/iristoapp-iris-messenger/issue/718).
