### ISSUE TITLE
get error

### ISSUE THREAD

**Issue by d4nm0** [irislib/iris-messenger#246]
Hi, I put my json file for the nip-05 validation. The problem is that on your web app it doesn't work while on other app it works.

![image](https://user-images.githubusercontent.com/20597792/217034380-ac7b2a3c-8f34-4990-9014-e4c3ee845105.png)

**Comment by mmalmi** [comment]
is CORS configured correctly?

**Comment by d4nm0** [comment]
![image](https://user-images.githubusercontent.com/20597792/217183535-1312c689-801e-4d76-8309-cda0c7d5d1f1.png)
yes i think

**Comment by mmalmi** [comment]
![Screenshot 2023-02-07 at 14 17 57](https://user-images.githubusercontent.com/2116445/217242891-19bf6e49-f75a-487c-9005-1bc06f2cd2a4.png)

**Comment by d4nm0** [comment]
my .htaccess :
<IfModule mod_rewrite.c>
  Header add Access-Control-Allow-Origin "*"
  Access-Control-Allow-Origin:*  
  Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
  Header add Access-Control-Allow-Headers: "Content-Type"

  RewriteEngine on
  RewriteBase /
</IfModule>

**Comment by d4nm0** [comment]
how to add header for danmonceau.fr without "www"

**Comment by d4nm0** [comment]
ah possible yes, indeed it works with www. do you know how to add also so that it works without www?

**Comment by d4nm0** [comment]
okay I'll have to see about removing the 'www' for now I'll use it. Thanks
