### ISSUE TITLE
git clone git@github.com:irislib/iris-messenger.git : Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by marcoippolito** [irislib/iris-messenger#26]
git clone git@github.com:irislib/iris-messenger.git
Cloning into 'iris-messenger'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mmalmi** [comment]
You probably need to set up a new key: https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

You can toggle between "Use SSH" and "Use HTTPS" when you click "Clone or download" on top of the repo. HTTPS doesn't require to set up a key: `git clone https://github.com/irislib/iris-messenger.git`
