### ISSUE TITLE
Rename Webtorrent to Media Menu. Add Audio, Social Media Playback Options. [UX][Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#261]
## User Story ##
As an Iris user that is looking to manage my media experience on Iris, I would like the option to turn off or on video, audio, and/or third party social media playback, so that I can configure Iris to my preferences.

### Acceptance Criteria ###
1. Rename webtorrent to Media in side menu
2. Add Video Playback title above webtorrent
3. Add Audio Playback section below
4. Add Social Media section below
5. Add checkmark options to disable/enable Tidal, Spotify in audio section, and IG in social media section

Current webtorrent menu view:
![Webtorrent Menu Current](https://user-images.githubusercontent.com/64376233/217925516-20736f0b-8c7a-47c8-ac46-a759e9fca2a2.png)

Suggested additions:
![Suggested Media Menu (2)](https://user-images.githubusercontent.com/64376233/217926383-b027ff64-bd77-4122-8fc3-d998a8f0ad77.png)

_Questions_
What are the default values? On? Off?
Can defaults be browser specific? For instance, on Tor Iris sessions, all playback is disabled by default.

**Comment by mmalmi** [comment]
Changed the settings menu

<img width="622" alt="Screenshot 2023-02-10 at 0 41 31" src="https://user-images.githubusercontent.com/2116445/217955641-b5578a91-a9db-46f8-a23d-eb43b8875e7f.png">
