### ISSUE TITLE
Images hosted on void.cat do not render on Iris [Bug][UX]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#272]
Unlike images hosted on nostr.build, images hosted on void.cat do not render on Iris.

**Comment by mmalmi** [comment]
Which browser? Can you give me a link for example?

https://iris.to/search/void.cat working normally for me

**Comment by mmalmi** [comment]
It's not an image url, so Iris doesn't know it's an image. Iris doesn't do generic url previews yet. Does that url work on some other client?
