### ISSUE TITLE
Add toggle: remove ♡❤️ (like) [UX][Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#290]
## User Story ##
As a low-time preference Iris user who wants to remove noise from my notes, I want an option to remove all ♡❤️ (like), so that I can only see the true signal of value & feedback - ⚡ (zaps).

### Acceptance Criteria ###
In settings menu, user can toggle (turn off, or turn on) ♡❤️ (like)
If ♡❤️ (like) toggle is off, timeline no longer shows ♡❤️ (like)
Reply, repost note, and zap spacing is equidistant after removal of ♡❤️

_Discussion_
Why not remove ♡❤️ (like) altogether? Facebook, tiktok, instagram etc. users will be used to seeing a certain pattern, and will expect to see ♡❤️ (like) option.

@mmalmi can Iris can measure what % if users opt to remove likes if you implement this feature request?

Mockups:
![Remove Heart (1)](https://user-images.githubusercontent.com/64376233/220172250-a95d9175-ba6f-4ca2-b041-419936ed7a18.png)

![Display Heart Toggle](https://user-images.githubusercontent.com/64376233/220172259-63d0a6c0-f99e-46c3-815a-e6aba47e22d7.png)

**Comment by joshr4** [comment]
In other words, are you requesting the ability to show/hide note reactions, specifically the "like" or "upvote" reaction ([NIP-25](https://github.com/nostr-protocol/nips/blob/master/25.md))?

**Comment by Chavao** [comment]
@mmalmi if you agree with this feature, I can implement it.

**Comment by petrikaj** [comment]
Did you notice there is a recent upgrade that allows to remove all the reactions from notes:

![](https://imgproxy.iris.to/insecure/rs:fit:1138:1138/plain/https://nostr.build/i/nostr.build_6d4f92769d95c6c40fa27b4bd6b7e9726f35f48535d08017a2028f3d019cd36e.png)

https://iris.to/note10v9e59a56gswzrjlxjwsszt4hzvl3p9tnxlpzswnl3xppaekv7xq60q7e6

**Comment by alltheseas** [comment]
> Did you notice there is a recent upgrade that allows to remove all the reactions from notes:

This a great. However, this lumps together all types of replies with reactions. 

As written the story asks to remove likes (❤️) only (i.e. not zaps, not replies).

The motivation behind the story is that there is signal in zaps ⚡, and there is less signal in likes (❤️ ). 

If a note that is high signal (⚡ zapped) contains replies, I would like to have the option of reading these.

**Comment by Chavao** [comment]
Yeah @petrikaj, I noticed that. But the @alltheseas' proposal is to remove only the ♡:heart:  button, giving focus to the zap ⚡ button.

**Comment by mmalmi** [comment]
Done
