### ISSUE TITLE
[BUG] Iris changing user relay list

### ISSUE THREAD

**Issue by bokybanton** [irislib/iris-messenger#294]
Again I don't know why but Iris is changing my relay list... It happens every day and it is very annoying.

**Comment by bokybanton** [comment]
maybe it is a nostr-tools bug.... Who knows. The lack of documentation on every client I tried so far is so disgusting. Even I don't know how to start to do this documentation to help people who start after us.

**Comment by petrikaj** [comment]
This is [documented](https://docs.iris.to/features/network) now.
