### ISSUE TITLE
Urgent Feature Request (Export / Import npubs of users i follow)

### ISSUE THREAD

**Issue by snapo** [irislib/iris-messenger#296]
Having in the settings a export menu point.

Export all npub's i follow
Import npubs to follow

Reason for this is within this week i lost already 2 times all the people i follow. Reason is 2 relays where down and i replaced them. Sometimes after doing this the relay list of iris gets reset to the default (for whatever reason, that is also a bug). But adding the relays back works.
Problem is everytime this happens i lose all people i follow, i did follow around 500 people and manually followed through search manualy people again. This is not feasible, especially after the second time this happens. As a emergency i would request (till this is fixed) a way for users to export at least the npubs they follow and let the users import them again in case something like this happens.

or is there a way to fix this issue in another way?

**Comment by mmalmi** [comment]
There's already "export raw data" in profiles which copies to clipboard your profile and contacts events. Just need to add "backup" to settings or somewhere so you can import events as json.

**Comment by mmalmi** [comment]
Relays have probably replaced your own follow events with a new event that doesn't have the follows.

I just added backup tools. https://iris.to/post/note1r77sdz20hd23ukdmvmg9x8j595v5dwk6e8k3emrfyc7ryl5uvt0qz9fvty

<img width="919" alt="Screenshot 2023-02-23 at 21 19 44" src="https://user-images.githubusercontent.com/2116445/221010139-88d7acb7-6483-4b45-bfd2-6c677f57f209.png">

**Comment by mmalmi** [comment]
> > Relays have probably replaced your own follow events with a new event that doesn't have the follows.
> > I just added backup tools. https://iris.to/post/note1r77sdz20hd23ukdmvmg9x8j595v5dwk6e8k3emrfyc7ryl5uvt0qz9fvty
> 
> Nice! @mmalmi does it make sense to automate the backup?

Yes, would make sense to automatically save the last 5 contact lists from separate days.
