### ISSUE TITLE
[FEATURE] Documentation for using iris

### ISSUE THREAD

**Issue by bokybanton** [irislib/iris-messenger#299]
Would like to help writing documentation for new users but I don't how to start even where to start writing. If somebody with more experience or main developer wants to start with a little guide or creating the first file, I will help pulling commits on this topic.

**Comment by mmalmi** [comment]
Here's the FAQ: https://github.com/irislib/faq

**Comment by petrikaj** [comment]
[docs.iris.to](https://docs.iris.to/features/network) is the latest upgrade.
