### ISSUE TITLE
I opened nostrich and Iris clients at same time using the same relays, but the show new messages appear first on Nostrich

### ISSUE THREAD

**Issue by bitcoinuser** [irislib/iris-messenger#301]
Hi,

I opened nostrich.com and Iristo clients at same time using the same relays, but the show new messages appear first on Nostrich. Any reason why this happens? can be improved?

Thanks.

**Comment by bitcoinuser** [comment]
Sometimes the button show new messages do not even appear on Iris, the new messages just jump in the screen after some minutes.

**Comment by petrikaj** [comment]
The latest [update](https://iris.to/note10v9e59a56gswzrjlxjwsszt4hzvl3p9tnxlpzswnl3xppaekv7xq60q7e6) changed a lot of the feed and relay handling. Closing for now but open a new issue if this still persist.
