### ISSUE TITLE
Blocking doesn't block all messages from an author

### ISSUE THREAD

**Issue by adamritter** [irislib/iris-messenger#312]
There's a spammer in https://iris.to/post/note1x54mmv7rnh055vgqqtn96vmucf6mnxrltv29uayuvd2kdkkyzckscj6ysh on my screen.

I tried to block him, but a lot of his notes remaned even after refreshing (maybe they are cached)

<img width="679" alt="Screenshot 2023-03-02 at 20 44 06" src="https://user-images.githubusercontent.com/58403584/222610922-a6e306fc-4879-445d-88e0-7b65f6da4947.png">

**Comment by petrikaj** [comment]
The feed handling has been rewritten so should be resolved.
