### ISSUE TITLE
[FEATURE] Spam filter

### ISSUE THREAD

**Issue by araujo88** [irislib/iris-messenger#314]
The client needs a filter for spam messages like these:

[
![image](https://user-images.githubusercontent.com/46436462/222755249-6a06b9d1-ef42-4593-90cb-1a394dc27d2d.png)
](url)

**Comment by petrikaj** [comment]
You can [mute](https://docs.iris.to/features/content#mute) a thread or [block](https://docs.iris.to/features/users#block) users as well as adjust the [social graph](https://docs.iris.to/features/content#feed) for better feed experience.
