### ISSUE TITLE
Images displayed at top of note instead of embedded

### ISSUE THREAD

**Issue by macterra** [irislib/iris-messenger#316]
[example](https://iris.to/post/note1qzph9zkt8umy43hps7cllmnkuwsawnkg3evdp705u2mwg4pat5tqj33lvm)

```
{
  "content": "Coming soon to NostrGram... https://media.nostrgram.co/i/5c/media_5c850989c4046.jpg",
  "created_at": 1678035343,
  "id": "0083728acb3f364ac6e187b1ffee76e3a1d74ec88e58d0f9f4e2b6e4543d5d16",
  "kind": 1,
  "pubkey": "597b42de56a9e0c19ee2d0cde5797dd58d48ce8dd25c732b4c873af11161f9fd",
  "sig": "eaf38eaeef71e31a5647fc55bdca03e40eb4e588b8e62a1c00ff3be898e640098dd94964d16c9cb6af33c86cb112a2238e34e40c071aeca44720b0558c09dad9",
  "tags": []
}
```

The content indicates the image should be displayed at the bottom of the note

![image](https://user-images.githubusercontent.com/434644/222981090-43a05100-b8c7-4910-9287-822becc7d5d4.png)

**Comment by macterra** [comment]
Another [test](http://localhost:8080/post/note1vag6he4ell8cufz0735s8tlu9vyhtehntgwkyerax2fymwat06ysrwg2xl)

```
{
  "kind": 1,
  "content": "test\n\nhttps://nostr.build/i/nostr.build_02cf2b56cf8da6337b269b0f2d7819ccc089886575d6cd9d86d4a0505bc06dbb.png\n\nembedding\n\nhttps://nostr.build/i/nostr.build_956e4f5f99ec8447fbe05d670c6a27f10e71fc27cf4af0109f567123d850938f.jpg\n\nimages\n\nhttps://nostr.build/i/nostr.build_0eb4796a0141908f2ea238e418cf2639bb629509d6d077ccd0bc57b42b4c107a.jpg\n\nin note",
  "tags": [],
  "created_at": 1678045838,
  "pubkey": "c1037c8ea6c90b1f59bcd55836eb9e6f440f601a1dedac3feea55dd95f4cd6ae",
  "id": "6751abe6b9ffcf8e244ff46903affc2b0975e6f35a1d62647d32924dbbab7e89",
  "sig": "eddf3dd5de128c436465a8256ea576481ee721838a7bc671ec185cdf10ed18ede305ec7fa7b03fab1a49f6047d97d16d972d5aff7cb028739e86d0ed38429440"
}
```

All 3 images are displayed at top of note:

![image](https://user-images.githubusercontent.com/434644/222982777-40e82b8e-3964-4124-a827-119022943071.png)

In contrast, coracle does worse by just displaying links:

![image](https://user-images.githubusercontent.com/434644/222982830-ac34a36a-2012-42ab-8d61-fe16664cfc16.png)

Amethyst does it right (I suggest), but my images are too big to screencap the whole message:

![image](https://user-images.githubusercontent.com/434644/222982874-32311114-ce96-4258-94f1-f51af961f00a.png)

**Comment by macterra** [comment]
Jokes don't really work when you display the punchline first 

![image](https://user-images.githubusercontent.com/434644/223567105-85c3782e-49ca-4fbe-ad1f-e00b8168420a.png)

**Comment by petrikaj** [comment]
inline picture format has been [implemented](https://iris.to/note1whajddeq50v6356rrt0jknetf40lchufr7f8y4kj8rwszp78w77sp4u9w4).
