### ISSUE TITLE
Relays take more than 10 seconds to connect

### ISSUE THREAD

**Issue by mdebus** [irislib/iris-messenger#325]
Some relays connect instantaneous (i.e. wss://nos.lol).

Some others (including mine) are taking more than 10 seconds:

wss://nostr.relayer.se (running strfry)
wss://nostr.data.haus (mine, running, nostr-rs-relay)
wss://rsslay.data.haus (mine, running rsslay)

Other clients (like snort) connect flawlessly.

My browser is Firefox.

**Comment by bleetube** [comment]
I think Firefox blocks the functionality of several nostr clients. At least with my FF profile (strict privacy policies, ublock, etc) none of them show global events. You could investigate what options you have to give up to get cross-site websockets working, or try another browser. Chromium seems to work for me, at least out of the box.

**Comment by mdebus** [comment]
Seems to be fixed by Commit #d49d3f6
