### ISSUE TITLE
followers less than real

### ISSUE THREAD

**Issue by mattn** [irislib/iris-messenger#329]
I have 630 followers but iris stops counting up at 260 when loading.

![image](https://user-images.githubusercontent.com/10111/225573636-dec00c70-3330-470e-9128-c7453cc6f6b4.png)

**Comment by petrikaj** [comment]
"The follower count is constructed from your social network's following lists. Iris gathers the data from relays and counts who is following you. There is no single "follower count" as in traditional centralised social media.

The follower count may vary between clients and sessions for this reason. Some relays may be offline or not accessible and therefore the current follower count reflects this. It does not necessarily mean that someone has unfollowed you."

https://github.com/irislib/faq#follower-count

**Comment by mattn** [comment]
I am using the same 4 relays for both iris and snort, but with different results.

**Comment by petrikaj** [comment]
Yes. It's a "feature" of nostr:

https://beta.iris.to/note1qlnqc0vvzq2rsqv8v8zukf939rd4euqtql7ewvz944gn4mm9lprqg59pr6

There's no follower count list and the concept is not defined at all in the protocol.

**Comment by mattn** [comment]
No, iris was showing 640 followers until recently. Recently, the number of followers has decreased.

**Comment by mattn** [comment]
I'm developing https://github.com/mattn/algia it algia can get 660 entries of followers.

**Comment by petrikaj** [comment]
<img width="782" alt="Screenshot 2023-03-23 at 10 10 57" src="https://user-images.githubusercontent.com/52623440/227142209-87eee7e3-b302-45f7-9df1-a495160bd049.png">

It seems you don't have too many relays. 

Your social network settings can affect the follower count as well:
https://github.com/irislib/faq#feed

Currently, there are some bugs in the feed so it could be just that as well.

Anyways, I would not pay too much attention to the whole notion of followers on nostr.

**Comment by susumuota** [comment]
I've been having the same problem for a few weeks now (or last week, I can't remember).

The number of followers in Snort is 175, but it's 101 in Iris. It used to be the same in the past.

**Comment by mattn** [comment]
Currently I have 660 followers and follow 640 people. If I click the "Follow All" button, my follow will be reduced to 290. This is a serious problem, I think.

**Comment by petrikaj** [comment]
A recent upgrade should have fixed this, and on nostr the [follower count](https://docs.iris.to/features/users#follower-count) is a lucid concept at best.
