### ISSUE TITLE
Adding a second reply to a message seems to break the system

### ISSUE THREAD

**Issue by mbrochh** [irislib/iris-messenger#33]
Not sure if this is something that would eventually resolve itself when the system had more time syncing.

Just now, I posted this reply to a message: https://iris.to/#/message/1x0hHOrUyg0UVs41KqdIIR6WKV3xRU2j7DOeXIvSNyI%3D

Then, right after that, I posted another reply to the same message: https://iris.to/#/message/TXTs6KyrwD3K3idGJiarSA6zKXWPiAGhc80IoXdAhYI%3D

Both my replies correctly show up in my timeline.

When I click at "Show replied message" on my first reply, I see the original message plus my reply. I would expect to see the whole thread, ie BOTH my replies.

Worse: When I click at "Show replied message" on my second reply, I STILL see the original message with my FIRST reply:

![image](https://user-images.githubusercontent.com/166590/95151221-b3663c80-07bc-11eb-94da-96976ecc52d1.png)

(In the screenshot, we see the original message, and my first reply, but I clicked at "Show replied message" on my second reply)

You can also see that the original message shows (2) near the speech bubble, but the page only shows one reply.

Seems like there is some bug here that prevents later replies from showing up and always just shows the first reply?

Hope this helps to track down the issue :)

**Comment by mmalmi** [comment]
This issue should be fixed now. Is it working for you?

**Comment by mmalmi** [comment]
Should be fixed now.
