### ISSUE TITLE
BUG; Profile data lost

### ISSUE THREAD

**Issue by zhihau** [irislib/iris-messenger#338]
I have edited my profile using iris web version in my android chrome. But one day I found that all the content in my profile was gone. How do I get back my profile data?

**Comment by adamritter** [comment]
What's your npub?

**Comment by zhihau** [comment]
Hi,
My npub is
npub1alk4cpe2tgxajeym8usmx232hxjsducmgrk8nrw80xv6ws90hn0stzvxqa

**Comment by petrikaj** [comment]
This is how it looked to me today. I manage to get your RAW json copy of your profile data if that helps (public profile menu options on Iris).

If you use the Restore option on Iris you should be able to get at least some of the info back: https://github.com/irislib/faq#backups-and-restore

(Rename the file from .txt to .json - Github did not accept .json ; or open the file and paste the content on the Restore field.

<img width="270" alt="Screenshot 2023-03-23 at 9 32 40" src="https://user-images.githubusercontent.com/52623440/227135457-72509dd6-9fba-4a24-ad64-c1bce6758cb2.png">
[zhihau.txt](https://github.com/irislib/iris-messenger/files/11048135/zhihau.txt)
