### ISSUE TITLE
CPU overload sometime prevents rendering [200k sats][bug]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#349]
> Iris CPU usage is not high, but something often blocks rendering (UI stuck). Will zap 100,000 sats for finding out what causes it and another 100,000 for fixing. I need a break 😄
- @mmalmi 

https://iris.to/note10q2c0s9ut3lf333c47cjae9drn0jhm73vd8tjpjx5nzwfj7yt0sshd3xrc

**Comment by mmalmi** [comment]
Fixed
