### ISSUE TITLE
Allow for anonymous "no name" sign up

### ISSUE THREAD

**Issue by thrownness** [irislib/iris-messenger#35]
Let someone sign up without filling in a name in the "name" field of the sign up page.

If they leave the field blank, just make their name a truncated public key or something.

Other users will still be able to give them "nicknames" when talking with them.

This would improve the usability for throwaway communication and decrease the sign up friction even further.

**Comment by mmalmi** [comment]
Interesting idea - why not. One option is a random generated funny name, as long as the generator lib is not too large.

**Comment by mmalmi** [comment]
Added an adjective + animal name generator.
