### ISSUE TITLE
Enable Private Relay Support [feature request][500k sats]

### ISSUE THREAD

**Issue by alltheseas** [irislib/iris-messenger#364]
As a Iris user who wants to connect with a particular group of nostriches privately, I want to be able to connect to a private relay, so that I can read and share notes only with a specific group of nostriches.

### Acceptance Criteria

1. Iris user can connect to a private relay
2. Iris user has a method to provide authentication details to a private relay
3. Iris user can check visually if they are successfully connected to the private relay
4. Iris user can remove a private relay
5. Iris user can de-authenticate from a private relay

_implementation details_
[NIP-42](https://github.com/nostr-protocol/nips/blob/master/42.md)

Origin: https://iris.to/note1c6khgk6phxzhq7hh2v32nhzrvlyn4y2ctk6h0kgtgfrgrh7y7e5qma8ykl

Additional context
Introduced feature request to Damus (iOS), and Amethyst (Android) as well.

Why is this important: private relays provide differentiation and novelty compared to incumbent twtr.

**Comment by nostr-wine** [comment]
We'll offer a 500k sats bounty per client for this feature.

**Comment by npub1zenn0** [comment]
'ello, letting you know that I've worked on it, https://github.com/irislib/iris-messenger/pull/370 hopefully merged soon.

I'll admit that the UX isn't exactly the friendliest of all, but I think it gets the job done for now.

**Comment by nostr-wine** [comment]
Awesome - thank you for working on this. I will add your pubkey to filter.nostr.wine right now so you can test that you are approved. I will note that the AUTH may not necessarily come on connect (as detailed in the NIP), so I'm not sure how Iris wants to handle this.

**Comment by nostr-wine** [comment]
Added!

**Comment by npub1zenn0** [comment]
Cool, thanks. The authentication works but I found another related issue, so that's useful

**Comment by nostr-wine** [comment]
Thank you! I'm trying to test this but I can't get Iris to only connect to relays on my list. My console log always has connection failures to relays that aren't on my list. Why? Is there a way I can make Iris ONLY use relays in my list so that I can test this?

**Comment by nostr-wine** [comment]
<img width="462" alt="Screenshot 2023-04-22 at 8 50 18 AM" src="https://user-images.githubusercontent.com/124309146/233785679-da4e7496-d637-435b-87c0-d8caeda3874c.png">

None of the failing relays are in my list...

**Comment by npub1zenn0** [comment]
Can you see if that happens in a private window?

**Comment by nostr-wine** [comment]
Same result. As soon as I login with my extension, it starts trying to connect to relays that aren't in my list. Interestingly, it seems to be a very old list (perhaps just based on popularity) because most of these relays are no longer functional.

relay.current.fyi
brb.io
relay.nostr.info

Seem to be the stickiest ones.

**Comment by npub1zenn0** [comment]
Yeah those are on the default relays list. Yeah I see the bug now too, will check in a bit.

**Comment by npub1zenn0** [comment]
Well, looks like making iris use a single relay is gonna be a massive hurdle so I'd rather not go down that road. The connection retry errors aren't really a problem.

I think best you can do to confirm that events are flowing is to check the websocket events in the devtools network tab:

![image](https://user-images.githubusercontent.com/129284607/233827812-400dbe3c-29a3-4bf6-8973-e81dc2e60152.png)

**Comment by nostr-wine** [comment]
Sorry for the delay! I was able to verify this. Thank you so much. Can I zap you as payment?

**Comment by npub1zenn0** [comment]
No problem at all. Yeah, zap is good! Thanks.

**Comment by nostr-wine** [comment]
Paid! Thanks again.

**Comment by npub1zenn0** [comment]
Got it. Big thanks!
