### ISSUE TITLE
Combine `Relay.ts` and `PubSub.ts`?

### ISSUE THREAD

**Issue by npub1zenn0** [irislib/iris-messenger#371]
@mmalmi what do you think of this, is this something that can feasibly be done?

I have a problem now in https://github.com/irislib/iris-messenger/pull/370 , because the client connects to the same relay multiple times. Every connection needs its own auth.

From what I can see, it looks a bit like `Relay.ts` is connecting for metadata, while `PubSub` is connecting for notes etc. correct me if I'm wrong on that.

**Comment by mmalmi** [comment]
I will make Relays.ts only handle the relay list and not initiate connections. Requests are already made from PubSub.ts via [relaypool](https://github.com/adamritter/nostr-relaypool-ts) — I'll also make publishing go through it.

**Comment by npub1zenn0** [comment]
That sounds good. Using the relaypool in Relays.ts seems like a plan.

**Comment by npub1zenn0** [comment]
This seems done.
