### ISSUE TITLE
Shared `.put()` variables for groups

### ISSUE THREAD

**Issue by thrownness** [irislib/iris-messenger#38]
I'd like to be able to customize the background of a chat, or the default emoji, or the avatar.

But that would only be fun if my friends in the group also saw those changes.

Putting these customization options in shared "put" values would also make my changes carry over to multiple devices.

This shared put would also be fun for nicknames (which are currently implemented on the user put values only). If implemented for group nicknames, then the concept of "contact nicknames" (only I see these) would become something different than "group nicknames" (everyone in the group sees these).

**Comment by petrikaj** [comment]
Iris is a nostr client now.
