### ISSUE TITLE
Logged in with my nsec key and ... broke it?

### ISSUE THREAD

**Issue by IngwiePhoenix** [irislib/iris-messenger#401]
I have no idea what happened here.

Downloaded the App's MSI installer (0.1.0) linked from the README, opened it, opted to use my private key, saw no messages and clicked on Settings and...

![image](https://github.com/irislib/iris-messenger/assets/2893716/9239d2bc-09c3-4dd4-8b8e-0e494f3bbb79)

Any clues?

pubkey: `npub1tcekjparmkju6k83r5tzmzjvjwy0nnajlrwyk35us9g7x7wx80ys9hjmky`

**Comment by telamon** [comment]
I've experienced something similar on first run in Firefox. In my case i had to simply restart the browser and all the spooks went away.

**Comment by IngwiePhoenix** [comment]
Did that and now I can log in. That's so odd though.

That said, it seems like this UI is much older than th e live one at iris.to - the entire "iris.to Settings" is missing from the settings panel. And, it isn't giving me new messages from the global view... Just my own.

But hey, one step at a time. It seems to work, somewhat, now.
