### ISSUE TITLE
Android App Like and Zap button behavior 

### ISSUE THREAD

**Issue by thomasanderson88** [irislib/iris-messenger#407]
On Android app, trying to touch the number of likes or zaps doesn’t open the count or profile. Instead it likes my own note or opens the zap dialog to zap my own note.

**Comment by mmalmi** [comment]
<img width="1186" alt="Screenshot 2023-07-02 at 10 29 31" src="https://github.com/irislib/iris-messenger/assets/2116445/d8afac47-34aa-44a7-a8e5-2a2af65235fa">

Like, zap and repost lists are now found on the post page.
