### ISSUE TITLE
Dev mode redirects to https

### ISSUE THREAD

**Issue by timjrobinson** [irislib/iris-messenger#41]
I just tried running Iris in dev mode following the instructions but it always redirects to https (it looks like https://github.com/irislib/iris-messenger/blob/master/src/js/lib/sea.js#L39 does it) which causes it to fail to load (as I have no SSL certificate setup for local network IP's). How do you get around this issue? 

Edit: It looks like `localhost:8080` works and doesn't redirect. But when running on my home server where I go to `SERVER_IP:8080` it redirects and fails with the SSL error.

**Comment by mmalmi** [comment]
I think that's the side effect of using webcrypto: it requires https except for localhost. Unfortunately, I don't think there's a way around it.

**Comment by mmalmi** [comment]
I was just serving gun (which now comes with iris-messenger) on my local network and had to add self-signed SSL certificates to make it work with https. Unfortunately, some browsers don't let you bypass the self-signed certificate warning. Perhaps more convenient is to just run [iris-electron](https://github.com/irislib/iris-electron).
