### ISSUE TITLE
Feature Request: Add back button to desktop app

### ISSUE THREAD

**Issue by gashihiko** [irislib/iris-messenger#415]
Please add back button to the desktop app as well as other versions. Now I have nowhere to click to go back. Only sending Alt+Left can do it. I'm using Windows10.
From this
![desktop image](https://github.com/irislib/iris-messenger/assets/32293016/5cd0c7e7-da87-4db8-9ef0-ebabe3be42e1)
To this
![browser image](https://github.com/irislib/iris-messenger/assets/32293016/054b3f83-d6d4-4796-b37c-d0d7c4a5e094)

**Comment by mmalmi** [comment]
Published v0.2.0 which is up to date with the web version. https://github.com/irislib/iris-messenger/releases/tag/app-v0.2.0
