### ISSUE TITLE
Cannot get Desktop Iris browser to sign in with my keys, creates new name, no followers. Follow me back Sirius :)

### ISSUE THREAD

**Issue by Satoshi0x** [irislib/iris-messenger#43]
[FIwZmXUOA0_2gqQ0iv9YUr52YV6UIm1sR-q5tBfA34g 2ev6f1BlSMvLrGUVseKSKFMu1RxxlSrJ3J2BvQdzKxQ](https://user-images.githubusercontent.com/48847567/103143123-5d77a580-46d6-11eb-8135-bf159b07e768.png)

**Comment by mmalmi** [comment]
Followed (better late than never)
