### ISSUE TITLE
How to search post content. Hashtags? 

### ISSUE THREAD

**Issue by thrownness** [irislib/iris-messenger#47]
How do we implement the searching of posts and not just searching of users?

Is it feasible to search the content of every post of everyone within 2 degrees? If not, is it _more_ feasible if you're only searching through hashtags?

---

Hashtags could be implemented through a field like this, below the existing text input box: https://github.com/developit/preact-token-input

Does each hashtag become it's own global index? eg. All posts with "harrypotter" tag are added to a node like `('tags').('harrypotter').(postAddress)`? Would that make it more performant to find relevant details? If so, does it defeat the purpose of the degrees of separation (first finding results from 1st degree, then from 2nd degree, then 3rd)?

**Comment by pwFoo** [comment]
Hashtags would be great and also mention persons / contacts?

**Comment by mmalmi** [comment]
It would be possible to search through all posts. If scalability becomes an issue, we can come up with some indexing solution.

**Comment by pwFoo** [comment]
Are hashtags removed from iris? Searching by hashtag haven't worked, but there was a hashtag list and filter right side? Also hashtags no more clickable in posts.

**Comment by mmalmi** [comment]
I removed hashtags, because they were broken and I didn't have time to maintain.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
