### ISSUE TITLE
Base64 Sticker Packs

### ISSUE THREAD

**Issue by thrownness** [irislib/iris-messenger#50]
Im thinking of a global library of sticker packs.

Users can basically “bookmark” the location of their favorite sticker packs. Their list of bookmarked packs are saved in their encrypted user graph. 

In chats or even in posts/comments, they can access their bookmarked sticker packs to use. 

Maybe there’s a sticker uploader app/service that looks kinda like https://readthis.space architecturally

thoughts? Perhaps there’s a more performant / efficient data format than base64. But that’s what works natively with gun right now, so idk.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
