### ISSUE TITLE
Share and poll feature as implemented in social.iris.to?

### ISSUE THREAD

**Issue by pwFoo** [irislib/iris-messenger#52]
Found social.iris.to and liked it, installed iris-messenger to compare.

Is it planned to add share, poll and upload files features?

![image](https://user-images.githubusercontent.com/333408/115613590-deddee00-a2ec-11eb-945b-e9249b4b733f.png)

![image](https://user-images.githubusercontent.com/333408/115613633-edc4a080-a2ec-11eb-8ad5-cd2ad10b0c25.png)

**Comment by mmalmi** [comment]
I'll add share / retweet. I'm interested in doing WebRTC direct file send at some point. Polls and arbitrary file attachments would be nice to have, but personally, not a high priority atm. Feel free to implement 😉

**Comment by pwFoo** [comment]
I think my request is low prio 👍

Performance and maybe loading indicaters would be higher priority?
