### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by veritas44** [irislib/iris-messenger#55]
Any futhure option to integrate/upload video in to post?

**Comment by mmalmi** [comment]
Yes, that would be cool & useful. Currently you can create a torrent file that has an .mp4 in it and paste the magnet link into the Iris comment field — that may work in the meantime.

**Comment by mmalmi** [comment]
Unfortunately, I don't think there's a good way to create and persist torrents in the browser. That would be easier to do in the desktop version of Iris.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
