### ISSUE TITLE
Detect updates

### ISSUE THREAD

**Issue by pwFoo** [irislib/iris-messenger#57]
Iris should detect updates of source files and show a reload button to refresh files, data and service worker if needed?

**Comment by mmalmi** [comment]
Iris service worker uses the stale-while-revalidate caching pattern: it serves the old version from cache and updates cache in the meantime, to be served on the next page load.

**Comment by pwFoo** [comment]
But Iris misses a way to force a reload. I use it as chrome fullscreen app and don't know if / when webapp reloads?

**Comment by mmalmi** [comment]
Webapp uses the same service worker thing. Ctrl (cmd) + shift + R should do a force refresh?

**Comment by pwFoo** [comment]
How to do ` Ctrl (cmd) + shift + R ` with my mobile? Is that possible?

**Comment by petrikaj** [comment]
Iris is a nostr client now.
