### ISSUE TITLE
page is jumping because of async post / image loading

### ISSUE THREAD

**Issue by pwFoo** [irislib/iris-messenger#58]
Because of async posts and image loading the page sometimes jumps after scrolled because of a async added image. Would it possible to insert loaded posts before and after the current page position and regardless keep the page at place without jumping up or down?

**Comment by trosel** [comment]
The jumping of the page does give off a “cheap” or “fragile” feeling.

**Comment by mmalmi** [comment]
If no one's volunteering, we could hire someone from upwork.com to try and make it work. I hate the infinite scroll stuff and feel like there's more important things I need to do 😄

**Comment by trosel** [comment]
@mmalmi not a bad idea!

it might need a combination of things (blur up photo loading, placeholder divs of a certain size, etc)

**Comment by petrikaj** [comment]
Iris is a nostr client now.
