### ISSUE TITLE
privacy information in About page needs more info

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#73]
when does the user expose their IP address and who can see that?

is IP only exposed when they use torrents? to who?

is IP exposed to relay node operators and not to other users?

**Comment by alltheseas** [comment]
@trosel Iris added to FAQ privacy on relays section. See: https://github.com/irislib/faq#privacy-on-relays, and the related privacy sections above this one.

If this satisfies your question, can you kindly close this issue 🙏

**Comment by petrikaj** [comment]
Iris is a nostr client now.
