### ISSUE TITLE
allow users to add custom key:value pairs to their profile

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#74]
Users should be able to add key value pairs like

twitter: link
youtube: link
monero: address
location: country
pronouns: blah / blah 

etc 

Then clients like Iris (or any other one) can hook into these keys and optionally do special things with them.

**Comment by mmalmi** [comment]
This is technically easy, you can already add custom pairs to your public profile at https://iris.to/explorer. Then it's just up to creating an intuitive, unobtrusive and mobile-friendly UI for this on the profile page.

**Comment by trosel** [comment]
The current way to edit the profile is not very clear anyway actually. I think having standard input boxes for even the name/bio (as well as key:value) may be a more straightforward UX

**Comment by petrikaj** [comment]
Iris is a nostr client now.
