### ISSUE TITLE
iris.to down?

### ISSUE THREAD

**Issue by VzxPLnHqr** [irislib/iris-messenger#78]
Hi there, I have been exploring Iris.to a bit (and some alternatives like https://github.com/fiatjaf/nostr ) However, it appears to me that the primary Gun DB peer for iris.to is down right now? When using the webapp, the little connection icon in the top-left says that I am connected to 0 peers.

**Comment by trosel** [comment]
Regarding Nostr, I wasn't aware of it but it seems very cool. Off the top of my head, what I like about Iris (and Gun) is that 

1. it allows for multi-device (your key is in the cloud, not on specific devices)
2. it allows for deleting data (not sure if Nostr passes around delete requests or not)
3. the data structure is just a graph, for everything. It's universal and easy to work with once you get the hang of it.

Both of these projects suffer from being divorced from economic incentives (and thus lack of node operators etc). Tokenized projects similar to these would be [Session](https://github.com/oxen-io), [Status](https://status.im/), [Sylo](https://www.sylo.io/wallet/the-difference/), etc. But none of these tokenized alternatives have an open SDK yet.
