### ISSUE TITLE
not all products load in store

### ISSUE THREAD

**Issue by itsvetobaby** [irislib/iris-messenger#81]
hey, its not a problem when visiting you own store (/store) but when visiting /store/pub whether is yours or another persons, only the first product loads out of all of them. sometimes you can spam refresh and it will fix it.
![Screen Shot 2021-11-20 at 8 35 36 PM](https://user-images.githubusercontent.com/68570004/142718610-9509261e-6608-4faa-a6ab-f5305e6d881c.png)
![Screen Shot 2021-11-20 at 8 36 02 PM](https://user-images.githubusercontent.com/68570004/142718612-a1dc5842-bb89-4355-85e0-04a09ac61490.png)

Any help would be really appreciated thanks

**Comment by petrikaj** [comment]
Iris is a nostr client now.
