### ISSUE TITLE
npm run dev doesn't serve non index.html files

### ISSUE THREAD

**Issue by timaschew** [irislib/iris-messenger#91]
If I start the dev server via `npm run dev` and open http://localhost everting is fine. But if I go to my profile page and, for example http://localhost:8080/profile/vkvbNT8FzMdgQkcZq6hYTRKK5CKopER1mxEolID8c9I.dKYviRRETgw70asvUlRGg_xXQiLm7PDGNGFqctdX5y0 and refresh the page I get an error: 

> Cannot GET /profile/vkvbNT8FzMdgQkcZq6hYTRKK5CKopER1mxEolID8c9I.dKYviRRETgw70asvUlRGg_xXQiLm7PDGNGFqctdX5y0

It works fine with `npm run build && npm run serve`

**Comment by petrikaj** [comment]
Iris is a nostr client now.
