### ISSUE TITLE
Lot of issues (with a local gun server)

### ISSUE THREAD

**Issue by timaschew** [irislib/iris-messenger#92]
I've hardcoded my local gun server and disabled the remotes:

```js
// DEFAULT_PEERS['https://gun-rs.iris.to/gun'] = {};
// DEFAULT_PEERS['https://gun-us.herokuapp.com/gun'] = {};
DEFAULT_PEERS['http://localhost:8765/gun'] = {};
```

Then I tried to test iris msg on firefox and chrome on the same machine. Almost nothing worked as expected, I've recorded a video because it's easier then explaining: https://youtu.be/EQQmgVxIy_4

Code for local gun server:
```js
const GUN = require('gun')
const server = require('http').createServer().listen(8765);
const gun = GUN({
        radisk: false,
        localStorage: false,
        web: server
});
```
Installed gun via npm: `"gun": "^0.2020.1235"`

**Comment by timaschew** [comment]
I've copied profile links to iris.to not to my localhost, thast was the issue

**Comment by mmalmi** [comment]
It's linking to iris.to because localhost:8080 links wouldn't work for other users. Another reason is that I don't want to encourage users to log in to random hosts with their Iris private key. But should it still link to `window.location.host` for clarity?

**Comment by timaschew** [comment]
Of course localhost would not work, it was just for testing it locally.

> Another reason is that I don't want to encourage users to log in to random hosts with their Iris private key

You mean if I host my own version of iris-messenger on foobar.org a user would use his iris.to credentials?
I was not thinking about that case, for me it's obvious but I guess not for normal users that these could be two totally different web apps.

>  But should it still link to window.location.host for clarity?

Yes that would make sense. If somebody wants to do bad things he can do it anyway, it's not really hard to replace those places in the code which are hard-coded to iris.to ;)
But it would make testing things locally much more easier.
