### ISSUE TITLE
Some unexpected behaviour

### ISSUE THREAD

**Issue by timaschew** [irislib/iris-messenger#94]
I run iris-messenger locally with only a local gun server:

```js
// DEFAULT_PEERS['https://gun-rs.iris.to/gun'] = {};
// DEFAULT_PEERS['https://gun-us.herokuapp.com/gun'] = {};
DEFAULT_PEERS['http://localhost:8765/gun'] = {};
```

and opened a firefox and chrome browser and tried to figure out how data is synced and shown or not.

1. The message filter doesn't show other messages if it's set to `Everyone`. 
2. If user A follows user B, B doesn't get a notification that A following him
3. If I user A send a message to user B, user B doesn't see any new message, except B opens the deeplink for the conversation
4. On the contacts page the conuter of following users is wrong, it shows 2, but it should be 1. It's correct on the profile page

Issues 1, 2 nd 3 does not apply if B starts to follow A.

Here is a video which shows everything: https://youtu.be/uFkgEnqYx6o

**Comment by timaschew** [comment]
Actually I like it that I don't see any content until I follow someone.

But also it's important if user A starts to follow user B and see the content of B, B should be notified.
If B is not notified and not follow back A, he things nobody can see his content and even in his own profile the counter of followers is zero which is wrong.

**Comment by timaschew** [comment]
I can see (when not followed anyone) the public keys (IDs) of all users in the explorer at `All / Public / ContentAddressed` but `All / Public / Users` does only show me my own user. When I start to follow the other users they start to appear also under `All / Public / Users`

**Comment by petrikaj** [comment]
Iris is a nostr client now.
