### ISSUE TITLE
use Lightning + Escrow for store

### ISSUE THREAD

**Issue by trosel** [irislib/iris-messenger#97]
Just an idea, and low on the priorities of course, but if the store component used Lightning, it could hook into an escrow like Lightning Escrow https://lightningescrow.io/

see this comment for how the api works today https://stacker.news/items/12350

and maybe the user can specify which escrow they use in the future. 

or perhaps they can opt out of an escrow if they choose.

**Comment by petrikaj** [comment]
Iris is a nostr client now.
